<?php

namespace App\Http\Controllers\System;

use App\Enums\AssetStatus;
use App\Enums\DisposalMethods;
use App\Enums\MaintenanceType;
use App\Enums\ServiceTypes;
use App\Enums\WorkorderStatus;
use App\Enums\WorkorderType;
use App\Http\Controllers\Controller;
use App\Models\RequisitionWorkorder;
use App\Models\ServiceWorkorder;
use Illuminate\Http\Request;
use App\Models\Report;
use App\Models\Employee;
use App\Models\Asset;
use App\Models\Department;
use App\Models\DisposalWorkorder;
use App\Models\Category;
use App\Models\Supplier;
use App\Enums\ReportType;
use Barryvdh\DomPDF\Facade\Pdf;
use App\Http\Requests\ReportValidation;

class ReportsController extends Controller
{
    public function getReports(){
        $reports = Report::paginate(5);
        $columns = ['Report Code', 'Type', 'Generated By', 'Date', 'Actions'];
        $reportTypes = ReportType::cases();
        $assetStatus = AssetStatus::cases();
        $disposalMethods = DisposalMethods::cases();
        $workorderTypes = WorkorderType::cases();
        $serviceTypes = ServiceTypes::cases();
        $maintenanceTypes = MaintenanceType::cases();
        $employees = Employee::select('id', 'first_name', 'last_name')
            ->orderBy('first_name')
            ->orderBy('last_name')
            ->get()
            ->pluck('full_name', 'id');
        $departments = Department::orderBy('name')->pluck('name','id');
        $categories = Category::orderBy('name')->pluck('name','id');
        $suppliers = Supplier::orderBy('name')->pluck('name','id');
        return view('pages.reports', compact('reports', 'columns', 'reportTypes', 'employees', 'departments','categories', 'assetStatus','disposalMethods', 'workorderTypes',
                                    'serviceTypes', 'maintenanceTypes','suppliers'));
    }

    public function generateReport(ReportValidation $request){
        $validated = $request->validated();

        if($validated['report_type'] !== 'workorder'){
            $query = Asset::query();

            if($validated['category_id'] ?? null){
                    $query->where('category_id', $validated['category_id']);
            }
            if($validated['department_id'] ?? null){
                $query->where('department_id', $validated['department_id']); 
            }

            if($validated['status'] ?? null){
                if($validated['status'] === 'disposed'){
                    $query->withTrashed();
                    $query->where('status', $validated['status']);
                }else{
                    $query->where('status', $validated['status']);
                }
            }

            if($validated['report_type'] === 'asset'){
                if($validated['date_from'] && $validated ['date_to']){
                    $query->whereBetween('acquisition_date', [$validated['date_from'], $validated['date_to']]);
                }

                if($validated['custodian_id'] ?? null){
                    $query->where('custodian_id', $validated['custodian_id']);
                }

                $data = $query->get();
                $pdf = Pdf::loadView('reports.asset-report', compact('data'))->setPaper('a4', 'landscape');

                $filename = 'RPT-'.time().'.pdf';
                $pdf->save(storage_path('app/public/reports/' . $filename));
                $count = (Report::count() ?? 0) + 1;

                Report::create([
                    'report_code' => 'RPT-'.($count),
                    'report_type' => $validated['report_type'],
                    'generated_by' => auth()->user()->id,
                    'file_path' => $filename      
                ]);

                return $pdf->stream('asset-report.pdf');
            }elseif($validated['report_type'] === 'depreciation'){
                $data = $query->get();
                $pdf = Pdf::loadView('reports.depreciation-report', compact('data'))->setPaper('a4', 'landscape');

                $filename = 'RPT-'.time().'.pdf';
                $pdf->save(storage_path('app/public/reports/' . $filename));
                $count = (Report::count() ?? 0) + 1;

                Report::create([
                    'report_code' => 'RPT-'.($count),
                    'report_type' => $validated['report_type'],
                    'generated_by' => auth()->user()->id,
                    'file_path' => $filename      
                ]);

                return $pdf->stream('depreciation-report.pdf');
            }  
        }elseif($validated['report_type'] === 'workorder'){
            $woType = $validated['workorder_type'];
            if($woType === 'disposal'){
                $query = DisposalWorkorder::with(['asset' => function($q){
                    $q->withTrashed();
                }], 'workorder', 'asset.department')
                ->whereHas('workorder', function($q){
                    $q->where('status', WorkorderStatus::COMPLETED);
                });

                if($validated['disposal_date_from'] && $validated['disposal_date_to']){
                    $query->whereBetween('disposal_date', [$validated['disposal_date_from'], $validated['disposal_date_to']]);
                }

                if($validated['disposal_method'] ?? null){
                    $query->where('disposal_method', $validated['disposal_method']);
                }

                if($validated['department_id'] ?? null){
                    $query->whereHas('asset', function($q) use ($validated){
                        $q->where('department_id', $validated['department_id']);
                    });
                }

                $data = $query->get();
                $pdf = Pdf::loadView('reports.disposal-report', compact('data'))->setPaper('a4', 'landscape');

                $filename = 'RPT-'.time().'.pdf';
                $pdf->save(storage_path('app/public/reports/' . $filename));
                $count = (Report::count() ?? 0) + 1;

                Report::create([
                    'report_code' => 'RPT-'.($count),
                    'report_type' => $validated['report_type'],
                    'generated_by' => auth()->user()->id,
                    'file_path' => $filename      
                ]);

                return $pdf->stream('disposal-report.pdf');
            }elseif($woType === 'service'){
                $query = ServiceWorkorder::with(['asset' => function($q){
                    $q->withTrashed()->with('department');
                }], 'workorder')
                ->whereHas('workorder', function($q){
                    $q->where('status', WorkorderStatus::COMPLETED);
                });

                if($validated['service_date_from'] ?? null && $validated['service_date_to'] ?? null){
                    $query->whereHas('workorder', function($q) use ($validated){
                        $q->whereBetween('end_date', [$validated['service_date_from'], $validated['service_date_to']]);
                    });
                }

                if($validated['service_type'] ?? null){
                    $query->where('service_type', $validated['service_type']);
                }

                if($validated['maintenance_type'] ?? null){
                    $query->where('maintenance_type', $validated['maintenance_type']);
                }

                if($validated['department_id'] ?? null){
                    $query->whereHas('asset', function($q) use ($validated){
                        $q->where('department_id', $validated['department_id']);
                    });
                }

                $data = $query->get();
                $pdf = Pdf::loadView('reports.service-report', compact('data'))->setPaper('a4', 'landscape');

                $filename = 'RPT-'.time().'.pdf';
                $pdf->save(storage_path('app/public/reports/' . $filename));
                $count = (Report::count() ?? 0) + 1;

                Report::create([
                    'report_code' => 'RPT-'.($count),
                    'report_type' => $validated['report_type'],
                    'generated_by' => auth()->user()->id,
                    'file_path' => $filename      
                ]);
                return $pdf->stream('service-report.pdf');
            }elseif($woType === 'requisition'){
                $query = RequisitionWorkorder::with(['asset' => function($q){
                    $q->withTrashed()->with('department');
                }], 'workorder','supplier')
                ->whereHas('workorder', function($q){
                    $q->where('status', WorkorderStatus::COMPLETED);
                });

                if($validated['asset_filter'] === 'new'){
                    $query->whereNotNull('asset_name')->where('asset_name', '!=', '');
                }elseif($validated['asset_filter'] === 'old'){
                    $query->whereNull('asset_name');
                }

                if($validated['comp_date_from'] ?? null && $validated['comp_date_to'] ?? null){
                    $query->whereHas('workorder', function($q) use ($validated){
                        $q->whereBetween('end_date', [$validated['comp_date_from'], $validated['comp_date_to']]);
                    });
                }

                if($validated['supplier_id'] ?? null){
                    $query->where('supplier_id', $validated['supplier_id']);
                }

                if($validated['department_id'] ?? null){
                    $query->whereHas('asset', function($q) use ($validated){
                        $q->where('department_id', $validated['department_id']);
                    });
                }

                $data = $query->get();
                $pdf = Pdf::loadView('reports.requisition-report', compact('data'))->setPaper('a4', 'landscape');

                $filename = 'RPT-'.time().'.pdf';
                $pdf->save(storage_path('app/public/reports/' . $filename));
                $count = (Report::count() ?? 0) + 1;

                Report::create([
                    'report_code' => 'RPT-'.($count),
                    'report_type' => $validated['report_type'],
                    'generated_by' => auth()->user()->id,
                    'file_path' => $filename      
                ]);
                return $pdf->stream('requisition-report.pdf');
            }
        }
    }

    public function deleteReport($id){
        $report = Report::findOrFail($id);

        $path = storage_path('app/public/reports/' . $report->file_path);
        if(file_exists($path)){
            if(!unlink($path)){
                return redirect()->back()->with('error', 'Failed to delete report file!');
            }
        }

        $report->delete();
        return redirect()->route('reports.index')->with('success', 'Report successfully deleted!');
    }

    public function downloadReport($id){
        $report = Report::findOrFail($id);
        $path = storage_path('app/public/reports/' . $report->file_path);
        
        return response()->download($path, $report->report_code . '.pdf');
    }
}