<?php

namespace App\Http\Controllers\System;

use App\Enums\AssetStatus;
use App\Enums\DisposalMethods;
use App\Http\Controllers\Controller;
use App\Models\AssetDisposalLog;
use Illuminate\Http\Request;
use App\Models\Report;
use App\Models\Employee;
use App\Models\Asset;
use App\Models\Department;
use App\Models\Category;
use App\Models\Supplier;
use App\Enums\ReportType;
use Barryvdh\DomPDF\Facade\Pdf;
use App\Http\Requests\ReportValidation;
use App\Models\ActivityLog;
use App\Enums\ActivityAction;
use App\Enums\ActivityModule;

class ReportsController extends Controller
{
    public function getReports(Request $request){
        $query = Report::query();
        if(request('search')){
            $search = $request->input('search');
            $query->search($search);
        }
        $reports = $query->paginate(5);

        $columns = ['Report Code', 'Type', 'Generated By', 'Date', 'Actions'];
        $assets = Asset::get();
        $reportTypes = ReportType::cases();
        $assetStatus = AssetStatus::cases();
        $disposalMethods = DisposalMethods::cases();
        $employees = Employee::orderBy('name')->pluck('name','id');
        $departments = Department::orderBy('name')->pluck('name','id');
        $categories = Category::orderBy('name')->pluck('name','id');
        $suppliers = Supplier::orderBy('name')->pluck('name','id');
        return view('pages.reports', compact('reports', 'columns', 'reportTypes', 'employees', 'departments','categories', 'assetStatus','disposalMethods','suppliers', 'assets'));
    }

    public function generateReport(ReportValidation $request){
        $validated = $request->validated();

        try {
            $query = Asset::query();

            if($validated['category_id'] ?? null){
                $query->where('category_id', $validated['category_id']);
            }
            if($validated['department_id'] ?? null){
                $query->where('department_id', $validated['department_id']);
            }

            if($validated['status'] ?? null){
                if($validated['status'] === 'disposed'){
                    $query->withTrashed();
                    $query->where('status', $validated['status']);
                }else{
                    $query->where('status', $validated['status']);
                }
            }

            if($validated['report_type'] === 'asset'){
                if($validated['date_from'] && $validated ['date_to']){
                    $query->whereBetween('acquisition_date', [$validated['date_from'], $validated['date_to']]);
                }

                if($validated['custodian_id'] ?? null){
                    $query->where('custodian_id', $validated['custodian_id']);
                }

                $data = $query->get();
                $pdf = Pdf::loadView('reports.asset-report', compact('data'))->setPaper('a4', 'landscape');

                $filename = 'RPT-'.time().'.pdf';
                $pdf->save(storage_path('app/public/reports/' . $filename));
                $count = (Report::count() ?? 0) + 1;

                $report = Report::create([
                    'report_code' => 'RPT-'.($count),
                    'report_type' => $validated['report_type'],
                    'generated_by' => auth()->user()->id,
                    'file_path' => $filename
                ]);

                ActivityLog::log(ActivityModule::REPORT, ActivityAction::CREATED, "Generated " . $report->report_type->label() . " report");

                return $pdf->stream('asset-report.pdf');
            }elseif($validated['report_type'] === 'depreciation'){
                $data = $query->get();
                $pdf = Pdf::loadView('reports.depreciation-report', compact('data'))->setPaper('a4', 'landscape');

                $filename = 'RPT-'.time().'.pdf';
                $pdf->save(storage_path('app/public/reports/' . $filename));
                $count = (Report::count() ?? 0) + 1;

                $report = Report::create([
                    'report_code' => 'RPT-'.($count),
                    'report_type' => $validated['report_type'],
                    'generated_by' => auth()->user()->id,
                    'file_path' => $filename
                ]);

                ActivityLog::log(ActivityModule::REPORT, ActivityAction::CREATED, "Generated " . $report->report_type->label() . " report");

                return $pdf->stream('depreciation-report.pdf');
            }elseif($validated['report_type'] === ReportType::DISPOSAL->value){
                $logQuery = AssetDisposalLog::query();

                if($validated['asset'] ?? null){
                    $logQuery->where('asset_id', $validated['asset']);
                }

                if($validated['disposal_date_from'] ?? null && $validated ['disposal_date_to'] ?? null){
                    $logQuery->whereBetween('disposal_date', [$validated['disposal_date_from'], $validated['disposal_date_to']]);
                }

                if($validated['disposal_method'] ?? null){
                    $logQuery->where('disposal_method', $validated['disposal_method']);
                }

                $data = $logQuery->get();
                $pdf = Pdf::loadView('reports.disposal-report', compact('data'))->setPaper('a4', 'landscape');

                $filename = 'RPT-'.time().'.pdf';
                $pdf->save(storage_path('app/public/reports/' . $filename));
                $count = (Report::count() ?? 0) + 1;

                $report = Report::create([
                    'report_code' => 'RPT-'.($count),
                    'report_type' => $validated['report_type'],
                    'generated_by' => auth()->user()->id,
                    'file_path' => $filename
                ]);

                ActivityLog::log(ActivityModule::REPORT, ActivityAction::CREATED, "Generated " . $report->report_type->label() . " report");

                return $pdf->stream('disposal-report.pdf');
            }
        }catch(\Exception $e) {
            return redirect()->route("reports.index")->with('error', 'Something went wrong!');
        }


    }

    public function deleteReport($id){
        $report = Report::findOrFail($id);

        $path = storage_path('app/public/reports/' . $report->file_path);
        if(file_exists($path)){
            if(!unlink($path)){
                return redirect()->back()->with('error', 'Failed to delete report file!');
            }
        }

        $report->delete();
        return redirect()->route('reports.index')->with('success', 'Report successfully deleted!');
    }

    public function downloadReport($id){
        $report = Report::findOrFail($id);
        $path = storage_path('app/public/reports/' . $report->file_path);

        return response()->download($path, $report->report_code . '.pdf');
    }
}
